version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    volumes:
      - db_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    ports:
      - "8056:8055"
    environment:
      KEY: "superlongkey32chars"
      SECRET: "anotherlongsecret32chars"
      DB_CLIENT: "pg"
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
    depends_on:
      - db
    volumes:
      - uploads:/directus/uploads

volumes:
  db_data:
  uploads:
